### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/qgis-wfsOutputExtension#8]
I follow the instructions in the README file and I encountered the following error after apache2 restart: 

```
WARNING Python error[15902]: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgis-wfsOutputExtension-1'

16:34:41 WARNING Couldn't load plugin 'qgis-wfsOutputExtension-1.2.2'[15902]: Couldn't load plugin 'qgis-wfsOutputExtension-1.2.2'


ModuleNotFoundError: No module named 'qgis-wfsOutputExtension-1'


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgis-wfsOutputExtension-1'




Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]


QGIS version: 3.4.15-Madeira Madeira, e83d02e274


Python Path:

/usr/share/qgis/python//.local/share/QGIS/QGIS3/profiles/default/python/opt/qgis-server/plugins//.local/share/QGIS/QGIS3/profiles/default/python/plugins/usr/share/qgis/python/plugins/usr/lib/python36.zip/usr/lib/python3.6/usr/lib/python3.6/lib-dynload/usr/local/lib/python3.6/dist-packages/usr/lib/python3/dist-packages

```

If I change the name of the folder from qgis-wfsOutputExtension-1.2.2 to qgis-wfsOutputExtension I do not encountered errors but I do not see the new export formats available from lizmap. 

Any suggestion?

**Comment by rldhont** [comment]
Rename the folder to wfsOutputExtension

**Comment by rldhont** [comment]
And be sure that the metadata.tx and other file are in wfsOutputExtension folder.

**Comment by Gustry** [comment]
I have just generated the zip file and uploaded it to plugins.qgis.org

https://plugins.qgis.org/plugins/wfsOutputExtension/version/1.2.2/download/

**Comment by rmarzocchi84** [comment]
Ok, no error on apache  but the result do not change:

![Uploading Schermata del 2020-01-24 16-54-08.png…]()

**Comment by rmarzocchi84** [comment]
Now it works.. it seems a problem of apache restart
